app = "lastbulwark-bot"
primary_region = "mad"

[env]
  BOT_TOKEN = "8713414078:AAG93c5HIxwVTdFrSznmGlNRDiQG0DDYefg"
  SUPABASE_URL = "https://eaimxmiszkgyjarnlebi.supabase.co"
  SUPABASE_ANON_KEY = "sb_publishable_6Z6CRpzgkLDhMtm2lslaBw_g19HZdbu"
  MINI_APP_URL = "https://lastbostbender.github.io/lastBulwark/"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  script = "npm start"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
